### ISSUE TITLE
pls push docker image to docker hub

### ISSUE THREAD

**Issue by zhu327** [jaja123456789/jellyfin-rkmpp#104]
Does it support rk3399 to hardware encode?

pls push docker image to docker hub

try to build docker image, but get some errror:

Cloning into 'jellyfin-web'...
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...

info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/jellyfin-web/node_modules/optipng-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: /jellyfin-web/node_modules/optipng-bin
Output:
⚠ spawn Unknown system error -8
  ⚠ optipng pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c make install

**Comment by zhu327** [comment]
try to copy jellyfin-web from jellyfin/jellyfin:10.6.4

when finish build image run error

[11:46:40] [INF] [5] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 12/17/2021 02:00, which is 14:13:19.2938827 from now.
[11:46:40] [FTL] [5] Main: Error while starting server.
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.GetFFmpegVersion(String output)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersionInternal(String versionOutput)
   at MediaBrowser.MediaEncoding.Encoder.EncoderValidator.ValidateVersion()
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ValidatePath(String path, FFmpegLocation location)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.SetFFmpegPath()
   at Emby.Server.Implementations.ApplicationHost.RunStartupTasksAsync()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)

**Comment by zhu327** [comment]
Is it possible to update to the new version of jellyfin

**Comment by zhu327** [comment]
打了一个能用的镜像:

https://hub.docker.com/r/zhu327/jellyfin-rkmpp

**Comment by zhu327** [comment]
转码失败:

mpp[13577]: mpp_info: mpp version: c06639a2 author: sayon.chen    2021-12-17 [vepu540]: Fix me regs param cfg issue
mpp[13577]: mpp_rt: NOT found ion allocator
mpp[13577]: mpp_rt: found drm allocator
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_rkmpp) -> h264 (h264_rkmpp))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[aac @ 0x55b1b52e00] Using a PCE to encode channel layout "5.1(side)"
[h264_rkmpp @ 0x55b1b6c8f0] Failed to send packet to decoder (code = -11)
    Last message repeated 40 times
[h264_rkmpp @ 0x55b1b6c8f0] Failed to send packet to decoder (code = -11) -0.0kbits/s speed=N/A
    Last message repeated 15 times
Too many packets buffered for output stream 0:1.
[aac @ 0x55b1b52e00] Qavg: 65536.000
[aac @ 0x55b1b52e00] 2 frames left in the queue on closing
mpp[13577]: mpp_dec: reset at info change status
mpp[13577]: mpp_dec: task no send to hal que must clr current frame hal status
Conversion failed!
ffmpeg[13577]: mpp_mem_pool: put_pool found 1 used buffer size 192

**Comment by zhu327** [comment]
Linux version:

Rockpi 4B armbian RK3399

Linux version 4.4.213-rockchip64 (root@runner7) (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36)) ) #2 SMP Wed Aug 25 20:06:36 UTC 2021

build mmp from https://github.com/jaja123456789/mpp.git

```
root@rockpi-4b:~/ffmpeg# LD_LIBRARY_PATH=/root/ffmpeg ./ffmpeg -i /srv/dev-disk-by-uuid-1505e425-3c80-4ff8-8be1-e3313a7f44e6/Movies/Dune.2021.1080p.HDRip.X264-EVO.mkv -c:v h264_rkmpp -b:v 2048k -vf scale=1280:-1 -y test.mp4
ffmpeg version 4578ededda Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/ffmped_dir/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/ffmped_dir/ffmpeg_build/include --extra-ldflags=-L/ffmped_dir/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/ffmped_dir/ffmpeg_bin --disable-v4l2-m2m --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-rkmpp --enable-version3 --enable-libdrm --enable-libx265 --enable-nonfree
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, matroska,webm, from '/srv/dev-disk-by-uuid-1505e425-3c80-4ff8-8be1-e3313a7f44e6/Movies/Dune.2021.1080p.HDRip.X264-EVO.mkv':
  Metadata:
    title           : EVO
    encoder         : libebml v1.4.0 + libmatroska v1.6.1
    creation_time   : 2021-10-17T00:48:56.000000Z
  Duration: 02:28:56.17, start: 0.075000, bitrate: 4215 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(yuv420p) (tv, bt709, progressive), 1920x776, SAR 1:1 DAR 240:97, 25 fps, 25 tbr, 1k tbn, 50 tbc (default)
    Metadata:
      BPS-eng         : 3829635
      DURATION-eng    : 02:28:56.160000000
      NUMBER_OF_FRAMES-eng: 223404
      NUMBER_OF_BYTES-eng: 4277779762
      _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-10-17 00:48:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 384 kb/s (default)
    Metadata:
      title           : Surround
      BPS-eng         : 384000
      DURATION-eng    : 02:28:56.128000000
      NUMBER_OF_FRAMES-eng: 279254
      NUMBER_OF_BYTES-eng: 428934144
      _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-10-17 00:48:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
mpp[14681]: mpp_info: mpp version: caf2b394 author: Jason         2020-09-16 tmp fix
mpp[14681]: mpp_rt: NOT found ion allocator
mpp[14681]: mpp_rt: found drm allocator
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_rkmpp) -> h264 (h264_rkmpp))
  Stream #0:1 -> #0:1 (ac3 (native) -> aac (native))
Press [q] to stop, [?] for help
[aac @ 0x5598e9cb20] Using a PCE to encode channel layout "5.1(side)"
[h264_rkmpp @ 0x5598eb6690] Decoder noticed an info change (1920x776), format=0
mpp[14681]: mpp_info: mpp version: caf2b394 author: Jason         2020-09-16 tmp fix
mpp[14681]: h264e_api_v2: MPP_ENC_SET_PREP_CFG w:h [1280:517] stride [1280:528]
mpp[14681]: mpp_enc_v2: send header for codec/prep cfg change
mpp[14681]: h264e_api_v2: MPP_ENC_SET_RC_CFG bps 0 [0 : 0] fps [25:25] gop 12
mpp[14681]: mpp_enc_v2: send header for rc cfg change rc_mode/fps/gop
[h264_rkmpp @ 0x5598eb7300] Unsupport profile -99, force set to 100
[h264_rkmpp @ 0x5598eb7300] Unsupport level -99, force set to 51
mpp[14681]: mpp_enc_v2: send header for codec/prep cfg change
mpp[14681]: mpp_enc_v2: Please use MPP_ENC_GET_HDR_SYNC instead of unsafe MPP_ENC_GET_EXTRA_INFO
mpp[14681]: mpp_enc_v2: NOTE: MPP_ENC_GET_HDR_SYNC needs MppPacket input
Output #0, mp4, to 'test.mp4':
  Metadata:
    title           : EVO
    encoder         : Lavf58.29.100
    Stream #0:0: Video: h264 (h264_rkmpp) (High) (avc1 / 0x31637661), nv12, 1280x517 [SAR 1551:1552 DAR 240:97], q=2-31, 2048 kb/s, 25 fps, 12800 tbn, 25 tbc (default)
    Metadata:
      BPS-eng         : 3829635
      DURATION-eng    : 02:28:56.160000000
      NUMBER_OF_FRAMES-eng: 223404
      NUMBER_OF_BYTES-eng: 4277779762
      _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-10-17 00:48:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc58.54.100 h264_rkmpp
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1(side), fltp, 394 kb/s (default)
    Metadata:
      title           : Surround
      BPS-eng         : 384000
      DURATION-eng    : 02:28:56.128000000
      NUMBER_OF_FRAMES-eng: 279254
      NUMBER_OF_BYTES-eng: 428934144
      _STATISTICS_WRITING_APP-eng: mkvmerge v49.0.0 ('Sick Of Losing Soulmates') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-10-17 00:48:56
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc58.54.100 aac
mpp[14681]: mpp_enc_v2: mode fixqp bps [0:0:0] fps fix [25/1] -> fix [25/1] gop i [12] v [0]
mpp[14681]: rc_base: Assertion p failed at mpp_data_update_v2:93
Segmentation fault
```
